extraEnvVars:
  MLFLOW_ALLOWED_HOSTS: "*"

log:
  enabled: false

extraArgs:
  allowed-hosts: "*"

backendStore:
  databaseMigration: false
  databaseConnectionCheck: false
  defaultSqlitePath: /tmp/mlflow.db

artifactRoot:
  defaultArtifactRoot: ./mlruns
  defaultArtifactsDestination: ./mlartifacts
  proxiedArtifactStorage: false

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 512Mi
