apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: mlflow
      targetRevision: 1.8.1
      helm:
        releaseName: mlflow
        valueFiles:
          - $values/values/mlflow-values.yaml
    - repoURL: https://github.com/nickolas-z/goit-argo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
